### ISSUE TITLE
Displaying text when bar too small

### ISSUE THREAD

**Issue by Glideh** [lightdesign/LDProgressView#18]
When the bar is too small (<40) it would be cool to left align the value text into the bar container remaining space.

Example:
![screen shot 2014-08-25 at 12 04 34](https://cloud.githubusercontent.com/assets/1119270/4028619/d92dddba-2c3f-11e4-9d7b-d9a4f4326153.png)

I did it by overriding this method (to give an idea, not worth PR, a little bit dirty I think)

```objective-c
- (void)drawRightAlignedLabelInRect:(CGRect)rect {
    if (rect.size.width > 40 || (self.frame.size.width - rect.size.width) > 40) {
        UILabel *label = [[UILabel alloc] initWithFrame:rect];
        label.adjustsFontSizeToFitWidth = YES;
        label.backgroundColor = [UIColor clearColor];
        label.text = self.progressTextOverride ? self.progressTextOverride :
            [NSString stringWithFormat:@"%.0f%%", self.progress*100];
        label.font = [UIFont boldSystemFontOfSize:17-self.progressInset.floatValue*1.75];
        GLfloat posx;
        GLfloat width;
        BOOL baseLabelisBlack;
        if (rect.size.width > 40) {
            posx = rect.origin.x + 6;
            width = rect.size.width - 12;
            baseLabelisBlack = [self.color isLighterColor];
            label.textAlignment = NSTextAlignmentRight;
        } else {
            posx = rect.size.width + 6;
            width = self.frame.size.width - rect.size.width - 12;
            baseLabelisBlack = ![self.color isLighterColor];
            label.textAlignment = NSTextAlignmentLeft;
        }
        UIColor *baseLabelColor = baseLabelisBlack ?
            [UIColor blackColor] : [UIColor whiteColor];
        label.textColor = [baseLabelColor colorWithAlphaComponent:0.6];
        [label drawTextInRect:CGRectMake(posx, rect.origin.y, width, rect.size.height)];
    }
}
```

To be renamed to something like

```objective-c
- (void)drawAlignedLabelForBar:(CGRect)rect;
```

**Comment by mohpor** [comment]
Current implementation jumps the label as soon as the progress bar reaches a certain amount (and frankly truncates the text sometimes), I guess a better implementation could be like this:
if progress bar doesn't have enough space for text, put the text somewhere anchored to the left (or right based on alignment) of the progressive, let the progress bar fill it under the text, until it reaches to an amount big enough to contain the text, then the text will latch on to the progress bar's like before and moves with progress bar's end.
