### ISSUE TITLE
Bug - endless loop

### ISSUE THREAD

**Issue by sergiogiro6** [lightdesign/LDProgressView#20]
Hi, i find a endless loop.
It's always call the drawRect because you don't invalidate the timer. 
To fix that i think that you need to invalidate timer in the method: - (void)incrementAnimatingProgress after [self.animationTimer invalidate]; you need to [self.timer invalidate].

Regards,

Sergio

**Comment by rcdilorenzo** [comment]
I just looked at this and the timer seems necessary if the animation flag is `YES`.

**Comment by rcdilorenzo** [comment]
Let me know if you are seeing unexpected behavior. For now, I'll close the issue.

**Comment by vincentnock** [comment]
I think there is a problem with the interpretation of ```animate```
You seem to use the same variable to choose to animate the progress bar with the ```animationTimer``` AND the stripes with the ```timer```.

So, if the stripes are unwanted, the ```self.timer``` is unnecessarily called, and should never trigger.

**Comment by rcdilorenzo** [comment]
@vincentnock, would you mind creating an issue called "Unnecessary timer call" with this description? Thanks for the catch here.

**Comment by vincentnock** [comment]
@rcdilorenzo done !
