### ISSUE TITLE
Unnecessary timer call

### ISSUE THREAD

**Issue by vincentnock** [lightdesign/LDProgressView#22]
I think there is a problem with the interpretation of `animate`
The same variable is used to choose to animate the progress bar with the `animationTimer` AND the stripes with the `timer`.

So, if the stripes are unwanted, the `self.timer` is unnecessarily called, and should never trigger.

**Comment by rcdilorenzo** [comment]
Closed as stale. Please re-open with fix or new issue as necessary.
