### ISSUE TITLE
Vertical bar

### ISSUE THREAD

**Issue by katerinafotiou** [lightdesign/LDProgressView#23]
Can we make the progress bar vertical?

**Comment by rcdilorenzo** [comment]
You may try using `CGAffineTransform` on the layer to get the desired behavior. As of right now, I have not implemented this. If I get enough upvotes on this thread however, I might consider doing it. Otherwise, feel free to send in a pull-request! :-)

**Comment by katerinafotiou** [comment]
Thank you for your answer.
You are right. I tried this simple line of code  " progressView.transform = CGAffineTransformMakeRotation( M_PI * -0.5 ); "

and worked. 

Thank you!

**Comment by rcdilorenzo** [comment]
I'm always curious. Is this an app destined for the store? If so, I'd love to put it on the README so that others can see it in action.

**Comment by katerinafotiou** [comment]
Yes it's an app for the store! It will be at the store hopefully in few months.

**Comment by rcdilorenzo** [comment]
Cool. Let me know when it hits the store!

**Comment by katerinafotiou** [comment]
Sure! thank you again.
