### ISSUE TITLE
I have some problems when use this Third  party.

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [lightdesign/LDProgressView#27]
_progressView.type = LDProgressSolid;    _progressView.color = [UIColor orangeColor];   i use these two . but it doesn't work , the progressView  color is alway  green and isn't solid type .

**Comment by rcdilorenzo** [comment]
Hmm... I'll take a look and see what I can do.

**Comment by rcdilorenzo** [comment]
I've tried changing these properties in the demo project, and it seems to be working properly. Let me know if there are further details to reproduce this issue and I'll reopen this thread.

**Comment by MyOnlyOnlySunshine** [comment]
thanks   i will download your demo and see whether
 it works

**Comment by MyOnlyOnlySunshine** [comment]
thanks

**Comment by MyOnlyOnlySunshine** [comment]
I  use  xib  to drag it and in "View did Load"   to set it's properties ,but it also doesn't matter .  I am really confused . Maybe i have do  something wrong with my project.

**Comment by MyOnlyOnlySunshine** [comment]
it works l when i  set properties in "view will appear". my god ...
